version: '3'
services:
   db:
     image: postgres
     restart: always
     volumes:
       - ./pgdata:/var/lib/postgresql/data
     environment:
       POSTGRES_PASSWORD: secret

   grafana:
     depends_on:
       - db
     image: grafana/grafana
     ports:
       - "3000:3000"
     restart: always
     environment:
       GF_SERVER_ROOT_URL: http://grafana.server.name
       GF_SECURITY_ADMIN_PASSWORD: secret
